export default {
  legend: {
    options: {
      showWithBaseMapOnly: true,
      shape: 'circle',
    },
    data: {
      'PPR Recreation Centers': {
        'border-color': 'black',
        'border-style': 'solid',
        'border-weight': '0px',
        'width': '15px',
        'height': '15px',
        'font-size': '12px',
        'background-color': '#0F4D90',
      },
      'PPR Operations': {
        'border-color': 'black',
        'border-style': 'solid',
        'border-weight': '0px',
        'width': '15px',
        'height': '15px',
        'font-size': '12px',
        'background-color': '#a86518',
      },
      'Environmental Educations Centers': {
        'border-color': 'black',
        'border-style': 'solid',
        'border-weight': '0px',
        'width': '15px',
        'height': '15px',
        'font-size': '12px',
        'background-color': '#721817',
      },
      'Older Adult Centers': {
        'border-color': 'black',
        'border-style': 'solid',
        'border-weight': '0px',
        'width': '15px',
        'height': '15px',
        'font-size': '12px',
        'background-color': '#444444',
      },
      'Museums': {
        'border-color': 'black',
        'border-style': 'solid',
        'border-weight': '0px',
        'width': '15px',
        'height': '15px',
        'font-size': '12px',
        'background-color': '#B569C3',
      },
      'Libraries': {
        'border-color': 'black',
        'border-style': 'solid',
        'border-weight': '0px',
        'width': '15px',
        'height': '15px',
        'font-size': '12px',
        'background-color': '#506D0A',
      },
      'Other': {
        'border-color': 'black',
        'border-style': 'solid',
        'border-weight': '0px',
        'width': '15px',
        'height': '15px',
        'font-size': '12px',
        'background-color': '#BAAC2C',
      },
    },
  },
};
